// <auto-generated />
using GuessTheFlag.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuessTheFlag.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230911172107_Updates")]
    partial class Updates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuessTheFlag.Shared.Models.CountryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo (Brazzaville)"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Congo (Kinshasa)"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Korea, North"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 128,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 132,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 153,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 165,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 166,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 188,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 189,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("GuessTheFlag.Shared.Models.FlagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            ImgUrl = "Afghanistan.gif"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            ImgUrl = "Albania.gif"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            ImgUrl = "Algeria.gif"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 4,
                            ImgUrl = "Andorra.gif"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 5,
                            ImgUrl = "Angola.gif"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 6,
                            ImgUrl = "Antigua_and_Barbuda.gif"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 7,
                            ImgUrl = "Argentina.gif"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 8,
                            ImgUrl = "Armenia.gif"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 9,
                            ImgUrl = "Australia.gif"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 10,
                            ImgUrl = "Austria.gif"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 11,
                            ImgUrl = "Azerbaijan.gif"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 12,
                            ImgUrl = "Bahamas.gif"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 13,
                            ImgUrl = "Bahrain.gif"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 14,
                            ImgUrl = "Bangladesh.gif"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 15,
                            ImgUrl = "Barbados.gif"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 16,
                            ImgUrl = "Belarus.gif"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 17,
                            ImgUrl = "Belgium.gif"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 18,
                            ImgUrl = "Belize.gif"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 19,
                            ImgUrl = "Benin.gif"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 20,
                            ImgUrl = "Bhutan.gif"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 21,
                            ImgUrl = "Bolivia.gif"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 22,
                            ImgUrl = "Bosnia_and_Herzegovina.gif"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 23,
                            ImgUrl = "Botswana.gif"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 24,
                            ImgUrl = "Brazil.gif"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 25,
                            ImgUrl = "Brunei.gif"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 26,
                            ImgUrl = "Bulgaria.gif"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 27,
                            ImgUrl = "Burkina_Faso.gif"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 28,
                            ImgUrl = "Burundi.gif"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 29,
                            ImgUrl = "Cabo_Verde.gif"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 30,
                            ImgUrl = "Cambodia.gif"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 31,
                            ImgUrl = "Cameroon.gif"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 32,
                            ImgUrl = "Canada.gif"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 33,
                            ImgUrl = "Central_African_Republic.gif"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 34,
                            ImgUrl = "Chad.gif"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 35,
                            ImgUrl = "Chile.gif"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 36,
                            ImgUrl = "China.gif"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 37,
                            ImgUrl = "Colombia.gif"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 38,
                            ImgUrl = "Comoros.gif"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 39,
                            ImgUrl = "Congo_(Brazzaville).gif"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 40,
                            ImgUrl = "Congo_(Kinshasa).gif"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 41,
                            ImgUrl = "Costa_Rica.gif"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 42,
                            ImgUrl = "Croatia.gif"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 43,
                            ImgUrl = "Cuba.gif"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 44,
                            ImgUrl = "Cyprus.gif"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 45,
                            ImgUrl = "Czechia.gif"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 46,
                            ImgUrl = "Denmark.gif"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 47,
                            ImgUrl = "Djibouti.gif"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 48,
                            ImgUrl = "Dominica.gif"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 49,
                            ImgUrl = "Dominican_Republic.gif"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 50,
                            ImgUrl = "East_Timor.gif"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 51,
                            ImgUrl = "Ecuador.gif"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 52,
                            ImgUrl = "Egypt.gif"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 53,
                            ImgUrl = "El_Salvador.gif"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 54,
                            ImgUrl = "Equatorial_Guinea.gif"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 55,
                            ImgUrl = "Eritrea.gif"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 56,
                            ImgUrl = "Estonia.gif"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 57,
                            ImgUrl = "Eswatini.gif"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 58,
                            ImgUrl = "Ethiopia.gif"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 59,
                            ImgUrl = "Fiji.gif"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 60,
                            ImgUrl = "Finland.gif"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 61,
                            ImgUrl = "France.gif"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 62,
                            ImgUrl = "Gabon.gif"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 63,
                            ImgUrl = "Gambia.gif"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 64,
                            ImgUrl = "Georgia.gif"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 65,
                            ImgUrl = "Germany.gif"
                        },
                        new
                        {
                            Id = 66,
                            CountryId = 66,
                            ImgUrl = "Ghana.gif"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 67,
                            ImgUrl = "Greece.gif"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 68,
                            ImgUrl = "Grenada.gif"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 69,
                            ImgUrl = "Guatemala.gif"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 70,
                            ImgUrl = "Guinea.gif"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 71,
                            ImgUrl = "Guinea-Bissau.gif"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 72,
                            ImgUrl = "Guyana.gif"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 73,
                            ImgUrl = "Haiti.gif"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 74,
                            ImgUrl = "Honduras.gif"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 75,
                            ImgUrl = "Hungary.gif"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 76,
                            ImgUrl = "Iceland.gif"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 77,
                            ImgUrl = "India.gif"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 78,
                            ImgUrl = "Indonesia.gif"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 79,
                            ImgUrl = "Iran.gif"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 80,
                            ImgUrl = "Iraq.gif"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 81,
                            ImgUrl = "Ireland.gif"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 82,
                            ImgUrl = "Israel.gif"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 83,
                            ImgUrl = "Italy.gif"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 84,
                            ImgUrl = "Ivory_Coast.gif"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 85,
                            ImgUrl = "Jamaica.gif"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 86,
                            ImgUrl = "Japan.gif"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 87,
                            ImgUrl = "Jordan.gif"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 88,
                            ImgUrl = "Kazakhstan.gif"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 89,
                            ImgUrl = "Kenya.gif"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 90,
                            ImgUrl = "Kiribati.gif"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 91,
                            ImgUrl = "Korea,_North.gif"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 92,
                            ImgUrl = "Korea,_South.gif"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 93,
                            ImgUrl = "Kosovo.gif"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 94,
                            ImgUrl = "Kuwait.gif"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 95,
                            ImgUrl = "Kyrgyzstan.gif"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 96,
                            ImgUrl = "Laos.gif"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 97,
                            ImgUrl = "Latvia.gif"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 98,
                            ImgUrl = "Lebanon.gif"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 99,
                            ImgUrl = "Lesotho.gif"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 100,
                            ImgUrl = "Liberia.gif"
                        },
                        new
                        {
                            Id = 101,
                            CountryId = 101,
                            ImgUrl = "Libya.gif"
                        },
                        new
                        {
                            Id = 102,
                            CountryId = 102,
                            ImgUrl = "Liechtenstein.gif"
                        },
                        new
                        {
                            Id = 103,
                            CountryId = 103,
                            ImgUrl = "Lithuania.gif"
                        },
                        new
                        {
                            Id = 104,
                            CountryId = 104,
                            ImgUrl = "Luxembourg.gif"
                        },
                        new
                        {
                            Id = 105,
                            CountryId = 105,
                            ImgUrl = "Macedonia.gif"
                        },
                        new
                        {
                            Id = 106,
                            CountryId = 106,
                            ImgUrl = "Madagascar.gif"
                        },
                        new
                        {
                            Id = 107,
                            CountryId = 107,
                            ImgUrl = "Malawi.gif"
                        },
                        new
                        {
                            Id = 108,
                            CountryId = 108,
                            ImgUrl = "Malaysia.gif"
                        },
                        new
                        {
                            Id = 109,
                            CountryId = 109,
                            ImgUrl = "Maldives.gif"
                        },
                        new
                        {
                            Id = 110,
                            CountryId = 110,
                            ImgUrl = "Mali.gif"
                        },
                        new
                        {
                            Id = 111,
                            CountryId = 111,
                            ImgUrl = "Malta.gif"
                        },
                        new
                        {
                            Id = 112,
                            CountryId = 112,
                            ImgUrl = "Marshall_Islands.gif"
                        },
                        new
                        {
                            Id = 113,
                            CountryId = 113,
                            ImgUrl = "Mauritania.gif"
                        },
                        new
                        {
                            Id = 114,
                            CountryId = 114,
                            ImgUrl = "Mauritius.gif"
                        },
                        new
                        {
                            Id = 115,
                            CountryId = 115,
                            ImgUrl = "Mexico.gif"
                        },
                        new
                        {
                            Id = 116,
                            CountryId = 116,
                            ImgUrl = "Micronesia.gif"
                        },
                        new
                        {
                            Id = 117,
                            CountryId = 117,
                            ImgUrl = "Moldova.gif"
                        },
                        new
                        {
                            Id = 118,
                            CountryId = 118,
                            ImgUrl = "Monaco.gif"
                        },
                        new
                        {
                            Id = 119,
                            CountryId = 119,
                            ImgUrl = "Mongolia.gif"
                        },
                        new
                        {
                            Id = 120,
                            CountryId = 120,
                            ImgUrl = "Montenegro.gif"
                        },
                        new
                        {
                            Id = 121,
                            CountryId = 121,
                            ImgUrl = "Morocco.gif"
                        },
                        new
                        {
                            Id = 122,
                            CountryId = 122,
                            ImgUrl = "Mozambique.gif"
                        },
                        new
                        {
                            Id = 123,
                            CountryId = 123,
                            ImgUrl = "Myanmar.gif"
                        },
                        new
                        {
                            Id = 124,
                            CountryId = 124,
                            ImgUrl = "Namibia.gif"
                        },
                        new
                        {
                            Id = 125,
                            CountryId = 125,
                            ImgUrl = "Nauru.gif"
                        },
                        new
                        {
                            Id = 126,
                            CountryId = 126,
                            ImgUrl = "Nepal.gif"
                        },
                        new
                        {
                            Id = 127,
                            CountryId = 127,
                            ImgUrl = "Netherlands.gif"
                        },
                        new
                        {
                            Id = 128,
                            CountryId = 128,
                            ImgUrl = "New_Zealand.gif"
                        },
                        new
                        {
                            Id = 129,
                            CountryId = 129,
                            ImgUrl = "Nicaragua.gif"
                        },
                        new
                        {
                            Id = 130,
                            CountryId = 130,
                            ImgUrl = "Niger.gif"
                        },
                        new
                        {
                            Id = 131,
                            CountryId = 131,
                            ImgUrl = "Nigeria.gif"
                        },
                        new
                        {
                            Id = 132,
                            CountryId = 132,
                            ImgUrl = "North_Macedonia.gif"
                        },
                        new
                        {
                            Id = 133,
                            CountryId = 133,
                            ImgUrl = "Norway.gif"
                        },
                        new
                        {
                            Id = 134,
                            CountryId = 134,
                            ImgUrl = "Oman.gif"
                        },
                        new
                        {
                            Id = 135,
                            CountryId = 135,
                            ImgUrl = "Pakistan.gif"
                        },
                        new
                        {
                            Id = 136,
                            CountryId = 136,
                            ImgUrl = "Palau.gif"
                        },
                        new
                        {
                            Id = 137,
                            CountryId = 137,
                            ImgUrl = "Palestine.gif"
                        },
                        new
                        {
                            Id = 138,
                            CountryId = 138,
                            ImgUrl = "Panama.gif"
                        },
                        new
                        {
                            Id = 139,
                            CountryId = 139,
                            ImgUrl = "Papua_New_Guinea.gif"
                        },
                        new
                        {
                            Id = 140,
                            CountryId = 140,
                            ImgUrl = "Paraguay.gif"
                        },
                        new
                        {
                            Id = 141,
                            CountryId = 141,
                            ImgUrl = "Peru.gif"
                        },
                        new
                        {
                            Id = 142,
                            CountryId = 142,
                            ImgUrl = "Philippines.gif"
                        },
                        new
                        {
                            Id = 143,
                            CountryId = 143,
                            ImgUrl = "Poland.gif"
                        },
                        new
                        {
                            Id = 144,
                            CountryId = 144,
                            ImgUrl = "Portugal.gif"
                        },
                        new
                        {
                            Id = 145,
                            CountryId = 145,
                            ImgUrl = "Qatar.gif"
                        },
                        new
                        {
                            Id = 146,
                            CountryId = 146,
                            ImgUrl = "Romania.gif"
                        },
                        new
                        {
                            Id = 147,
                            CountryId = 147,
                            ImgUrl = "Russia.gif"
                        },
                        new
                        {
                            Id = 148,
                            CountryId = 148,
                            ImgUrl = "Rwanda.gif"
                        },
                        new
                        {
                            Id = 149,
                            CountryId = 149,
                            ImgUrl = "Saint_Kitts_and_Nevis.gif"
                        },
                        new
                        {
                            Id = 150,
                            CountryId = 150,
                            ImgUrl = "Saint_Lucia.gif"
                        },
                        new
                        {
                            Id = 151,
                            CountryId = 151,
                            ImgUrl = "Saint_Vincent_and_the_Grenadines.gif"
                        },
                        new
                        {
                            Id = 152,
                            CountryId = 152,
                            ImgUrl = "Samoa.gif"
                        },
                        new
                        {
                            Id = 153,
                            CountryId = 153,
                            ImgUrl = "San_Marino.gif"
                        },
                        new
                        {
                            Id = 154,
                            CountryId = 154,
                            ImgUrl = "Sao_Tome_and_Principe.gif"
                        },
                        new
                        {
                            Id = 155,
                            CountryId = 155,
                            ImgUrl = "Saudi_Arabia.gif"
                        },
                        new
                        {
                            Id = 156,
                            CountryId = 156,
                            ImgUrl = "Senegal.gif"
                        },
                        new
                        {
                            Id = 157,
                            CountryId = 157,
                            ImgUrl = "Serbia.gif"
                        },
                        new
                        {
                            Id = 158,
                            CountryId = 158,
                            ImgUrl = "Seychelles.gif"
                        },
                        new
                        {
                            Id = 159,
                            CountryId = 159,
                            ImgUrl = "Sierra_Leone.gif"
                        },
                        new
                        {
                            Id = 160,
                            CountryId = 160,
                            ImgUrl = "Singapore.gif"
                        },
                        new
                        {
                            Id = 161,
                            CountryId = 161,
                            ImgUrl = "Slovakia.gif"
                        },
                        new
                        {
                            Id = 162,
                            CountryId = 162,
                            ImgUrl = "Slovenia.gif"
                        },
                        new
                        {
                            Id = 163,
                            CountryId = 163,
                            ImgUrl = "Solomon_Islands.gif"
                        },
                        new
                        {
                            Id = 164,
                            CountryId = 164,
                            ImgUrl = "Somalia.gif"
                        },
                        new
                        {
                            Id = 165,
                            CountryId = 165,
                            ImgUrl = "South_Africa.gif"
                        },
                        new
                        {
                            Id = 166,
                            CountryId = 166,
                            ImgUrl = "South_Sudan.gif"
                        },
                        new
                        {
                            Id = 167,
                            CountryId = 167,
                            ImgUrl = "Spain.gif"
                        },
                        new
                        {
                            Id = 168,
                            CountryId = 168,
                            ImgUrl = "Sri_Lanka.gif"
                        },
                        new
                        {
                            Id = 169,
                            CountryId = 169,
                            ImgUrl = "Sudan.gif"
                        },
                        new
                        {
                            Id = 170,
                            CountryId = 170,
                            ImgUrl = "Suriname.gif"
                        },
                        new
                        {
                            Id = 171,
                            CountryId = 171,
                            ImgUrl = "Sweden.gif"
                        },
                        new
                        {
                            Id = 172,
                            CountryId = 172,
                            ImgUrl = "Switzerland.gif"
                        },
                        new
                        {
                            Id = 173,
                            CountryId = 173,
                            ImgUrl = "Syria.gif"
                        },
                        new
                        {
                            Id = 174,
                            CountryId = 174,
                            ImgUrl = "Taiwan.gif"
                        },
                        new
                        {
                            Id = 175,
                            CountryId = 175,
                            ImgUrl = "Tajikistan.gif"
                        },
                        new
                        {
                            Id = 176,
                            CountryId = 176,
                            ImgUrl = "Tanzania.gif"
                        },
                        new
                        {
                            Id = 177,
                            CountryId = 177,
                            ImgUrl = "Thailand.gif"
                        },
                        new
                        {
                            Id = 178,
                            CountryId = 178,
                            ImgUrl = "Togo.gif"
                        },
                        new
                        {
                            Id = 179,
                            CountryId = 179,
                            ImgUrl = "Tonga.gif"
                        },
                        new
                        {
                            Id = 180,
                            CountryId = 180,
                            ImgUrl = "Trinidad_and_Tobago.gif"
                        },
                        new
                        {
                            Id = 181,
                            CountryId = 181,
                            ImgUrl = "Tunisia.gif"
                        },
                        new
                        {
                            Id = 182,
                            CountryId = 182,
                            ImgUrl = "Turkey.gif"
                        },
                        new
                        {
                            Id = 183,
                            CountryId = 183,
                            ImgUrl = "Turkmenistan.gif"
                        },
                        new
                        {
                            Id = 184,
                            CountryId = 184,
                            ImgUrl = "Tuvalu.gif"
                        },
                        new
                        {
                            Id = 185,
                            CountryId = 185,
                            ImgUrl = "Uganda.gif"
                        },
                        new
                        {
                            Id = 186,
                            CountryId = 186,
                            ImgUrl = "Ukraine.gif"
                        },
                        new
                        {
                            Id = 187,
                            CountryId = 187,
                            ImgUrl = "United_Arab_Emirates.gif"
                        },
                        new
                        {
                            Id = 188,
                            CountryId = 188,
                            ImgUrl = "United_Kingdom.gif"
                        },
                        new
                        {
                            Id = 189,
                            CountryId = 189,
                            ImgUrl = "United_States.gif"
                        },
                        new
                        {
                            Id = 190,
                            CountryId = 190,
                            ImgUrl = "Uruguay.gif"
                        },
                        new
                        {
                            Id = 191,
                            CountryId = 191,
                            ImgUrl = "Uzbekistan.gif"
                        },
                        new
                        {
                            Id = 192,
                            CountryId = 192,
                            ImgUrl = "Vanuatu.gif"
                        },
                        new
                        {
                            Id = 193,
                            CountryId = 193,
                            ImgUrl = "Vatican_City.gif"
                        },
                        new
                        {
                            Id = 194,
                            CountryId = 194,
                            ImgUrl = "Venezuela.gif"
                        },
                        new
                        {
                            Id = 195,
                            CountryId = 195,
                            ImgUrl = "Vietnam.gif"
                        },
                        new
                        {
                            Id = 196,
                            CountryId = 196,
                            ImgUrl = "Yemen.gif"
                        },
                        new
                        {
                            Id = 197,
                            CountryId = 197,
                            ImgUrl = "Zambia.gif"
                        },
                        new
                        {
                            Id = 198,
                            CountryId = 198,
                            ImgUrl = "Zimbabwe.gif"
                        });
                });

            modelBuilder.Entity("GuessTheFlag.Shared.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GuessTheFlag.Shared.Models.FlagModel", b =>
                {
                    b.HasOne("GuessTheFlag.Shared.Models.CountryModel", "Country")
                        .WithOne("Flag")
                        .HasForeignKey("GuessTheFlag.Shared.Models.FlagModel", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GuessTheFlag.Shared.Models.CountryModel", b =>
                {
                    b.Navigation("Flag")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
